import { mkdirSync, writeFileSync } from 'node:fs';

// Meta CSP is supported by static GitHub Pages. Header-only protections such as
// frame-ancestors and HSTS must be configured at a hosting/proxy layer, not here.
const policy = "default-src 'none'; script-src 'self'; script-src-attr 'none'; style-src 'self' https://fonts.googleapis.com; style-src-attr 'none'; font-src https://fonts.gstatic.com; img-src 'self'; connect-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'; upgrade-insecure-requests";
const securityMeta = `<meta http-equiv="Content-Security-Policy" content="${policy}"><meta name="referrer" content="strict-origin-when-cross-origin">`;
const cleanPath = slug => slug==='index' ? '/' : `/${slug}/`;

const pages = [
  ['index','Home'],['technology','Technology'],['industries','Industries'],['solutions','Solutions'],['research','R&D'],['about','About'],['contact','Contact']
];
const link = (path, text, primary=false) => `<a class="button ${primary?'primary':''}" href="${path}.html">${text}<span aria-hidden="true">↗</span></a>`;
const label = text => `<p class="eyebrow">${text}</p>`;
const card = (n,title,body,tag='') => `<article class="card"><span class="number">${n}</span>${tag?`<span class="tag">${tag}</span>`:''}<h3>${title}</h3><p>${body}</p></article>`;
const intro = (n,title,body) => `<section class="page-intro wrap">${label(n)}<h1>${title}</h1><p class="lead">${body}</p></section>`;
const cta = `<section class="cta wrap"><div>${label('A conversation is the first step')}<h2>Bring us a<br><span>real-world challenge.</span></h2></div>${link('contact','Let’s talk',true)}</section>`;
const brand = `<a class="brand" href="index.html" aria-label="NorthBeam Robotics home"><span class="brand-symbol" aria-hidden="true">N</span><span>NORTHBEAM<small>R O B O T I C S</small></span></a>`;
const scene = (mode='brand') => `<div class="scene ${mode==='sense'?'sensor-scene':''}" data-scene="${mode}"><div class="scene-fallback" aria-hidden="true">N</div><canvas aria-label="${mode==='sense'?'Interactive conceptual 3D sensing illustration':'Interactive conceptual 3D NorthBeam N emblem'}" role="img"></canvas><div class="scene-top"><span>${mode==='sense'?'AUTONOMY / EXPLORER':'NORTHBEAM / FORM STUDY'}</span><span>3D</span></div><div class="scene-bottom"><span>${mode==='sense'?'SYNTHETIC DATA · NOT ROBOT TELEMETRY':'CONCEPTUAL BRAND VISUAL'}</span><button class="motion-toggle" type="button" aria-pressed="false">Pause motion</button></div></div>`;

const bodies = {
index: `<section class="home-hero wrap"><div class="hero-copy">${label('Robotics. Autonomy. Physical AI.')}<h1 class="autonomy-title">Building<br>autonomy for the<br><span>physical world.</span></h1><p class="lead">Autonomy software and integrated robotic systems for machines that sense, navigate and act.</p><p class="hero-detail">NorthBeam Robotics connects perception, localization, navigation and systems integration to help solve real-world challenges across industries.</p><div class="actions">${link('technology','Explore our technology',true)}${link('about','Meet NorthBeam')}</div></div>${scene()}</section>
<div class="signal-strip"><div class="wrap"><span>HYDERABAD, INDIA</span><span>PERCEPTION / LOCALIZATION / NAVIGATION</span><span>BUILT FOR THE PHYSICAL WORLD</span></div></div>
<section class="wrap section"><div class="section-heading">${label('01 / Our core capabilities')}<h2>Understand the world.<br><span>Move with purpose.</span></h2><p>Our focus is the autonomy that connects sensing to useful action. Three engineering capabilities form the foundation of our work.</p></div><div class="three-grid">${card('01','Perception & localization','Helping robots interpret sensor data, build spatial understanding and estimate their position within an environment.')}${card('02','Navigation & mobility','Connecting maps, motion planning and control so robots can move toward a task within defined operating conditions.')}${card('03','Integration & applied R&D','Bringing sensors, edge computing, ROS 2 software and robot platforms together, then evaluating how the system performs.')}</div><div class="section-link">${link('technology','Inside the autonomy stack')}</div></section>
<section class="industry-feature wrap"><div>${label('02 / Our focus')}<h2>From perception<br><span>to autonomous action.</span></h2><p>A robot needs more than individual algorithms. We connect sensing, localization, planning and control around the task, the platform and the environment.</p>${link('solutions','Explore our engineering focus')}</div><div class="feature-type"><span class="tag">AUTONOMY ACROSS APPLICATIONS</span><h3>Sense.<br>Navigate.<br>Integrate.<span class="outline-type">01</span></h3><p>One engineering foundation.<br>Different real-world challenges.</p></div></section>
<section class="wrap section"><div class="section-heading">${label('03 / Explore NorthBeam')}<h2>Engineering the<br><span>next chapter.</span></h2></div><div class="three-grid"><a class="editorial-card" href="solutions.html"><span class="number">SOLUTIONS</span><h3>From a challenge<br>to a scoped project.</h3><p>Explore possible ways to work together.</p><span class="card-link">Explore solutions ↗</span></a><a class="editorial-card" href="research.html"><span class="number">RESEARCH & DEVELOPMENT</span><h3>Progress starts<br>with better questions.</h3><p>Our technical priorities and validation approach.</p><span class="card-link">Inside R&D ↗</span></a><a class="editorial-card" href="about.html"><span class="number">THE COMPANY</span><h3>Built in Hyderabad.<br>Thinking beyond borders.</h3><p>The vision shaping NorthBeam Robotics.</p><span class="card-link">Our story ↗</span></a></div></section>${cta}`,
technology: `${intro('01 / Technology','From sensing<br>to <span>physical action.</span>','Our technical focus is ROS 2-based autonomy: connecting perception, localization, navigation and robot interfaces into systems that can be evaluated as a whole.')}
<section class="wrap explorer"><div class="explorer-heading"><div>${label('Explore the autonomy loop')}<h2>One environment.<br><span>Three perspectives.</span></h2></div><div class="mode-controls" role="group" aria-label="Visualization mode"><button data-mode="sense" aria-pressed="true">01 Sense</button><button data-mode="map" aria-pressed="false">02 Map</button><button data-mode="plan" aria-pressed="false">03 Plan</button></div></div>${scene('sense')}<div class="explorer-caption"><h3 id="mode-title">Sense the surroundings</h3><p id="mode-description" aria-live="polite">A synthetic point cloud illustrates how spatial measurements can describe surfaces and obstacles. This is an explanatory visual, not a working perception system.</p></div><noscript><p>The static view illustrates the sensing stage. Enable JavaScript to switch between sensing, mapping and planning.</p></noscript></section>
<section class="wrap section"><div class="two-grid">${card('01','Perception & sensor fusion','Combining 3D sensing and computer vision to estimate where objects and surfaces are, while accounting for incomplete or uncertain measurements.')}${card('02','Localization & mapping','Estimating a robot’s position within an environment. Robust operation depends on reference frames, map quality and recovery from localization loss.')}${card('03','Planning & motion control','Turning a task into a feasible path and controlled motion, with explicit operating limits and responses to obstacles.')}${card('04','ROS 2 & systems integration','Connecting sensor drivers, coordinate frames, robot interfaces and edge computing. Integration and validation turn separate components into a coherent robotic system.')}</div></section>
<section class="wrap inset-section">${label('Engineering principle')}<h2>Autonomy needs<br><span>boundaries.</span></h2><p class="lead">Defined operating conditions, human supervision, fault handling and task-specific validation belong in the design from the beginning.</p><p>These are engineering priorities, not a claim of certified safety or unrestricted autonomous operation.</p></section>${cta}`,
industries: `${intro('02 / Industries','Many industries.<br><span>One physical world.</span>','Our focus is autonomous robotics, not a single sector. We explore how perception, localization, navigation and integration can address different operational challenges.')}
<section class="wrap industry-lead"><div>${label('01 / Capability-led applications')}<h2>The environment changes.<br><span>The engineering connects.</span></h2><p class="lead">Start with the task. Identify what a robot needs to sense, where it needs to move and how it should respond.</p><p>The areas below are potential applications of our autonomy capabilities, not claims of completed deployments. Each project needs its own feasibility assessment, operating limits and validation.</p>${link('contact','Discuss your application',true)}</div><aside><h3>What we evaluate</h3><ul class="detail-list"><li><span>Task</span>The work and the outcome it must achieve</li><li><span>Environment</span>Terrain, visibility, obstacles and operating constraints</li><li><span>Integration</span>Sensors, computing and robot interfaces</li><li><span>Validation</span>Performance, recovery and human supervision</li></ul></aside></section>
<section class="wrap section"><div class="section-heading">${label('02 / Application areas')}<h2>Different industries.<br><span>Shared capabilities.</span></h2><p>Areas for project exploration. Technical scope and readiness are assessed individually.</p></div><div class="two-grid">${card('01','Industrial environments','Explore spatial perception, autonomous inspection and mobile robot integration around industrial operating constraints.','POTENTIAL APPLICATION')}${card('02','Logistics & material movement','Explore localization, obstacle-aware navigation and robot integration for movement within operational spaces.','POTENTIAL APPLICATION')}${card('03','Inspection & asset intelligence','Explore mobile sensing and visual analysis to support inspection and help people understand asset condition.','POTENTIAL APPLICATION')}${card('04','Construction & infrastructure','Explore mapping, site inspection and task-specific automation, including overhead installation concepts where feasible.','POTENTIAL APPLICATION')}</div></section>${cta}`,
solutions: `${intro('03 / Solutions','The right approach.<br><span>For the actual work.</span>','Our engineering focus spans perception and localization, autonomous navigation, and robotics integration. These are starting points for project discussions; scope, feasibility and availability are agreed individually.')}
<section class="wrap solution-list"><article><span class="number">01</span><div><span class="tag">PROJECT DISCUSSION</span><h2>Perception & localization</h2><p>Explore how your robot can interpret its surroundings and estimate its position using 3D sensing, computer vision and spatial maps.</p><ul><li>Sensor integration and point-cloud processing</li><li>Mapping, localization and coordinate-frame alignment</li><li>Accuracy, uncertainty and recovery requirements</li></ul></div>${link('contact','Discuss perception')}</article><article><span class="number">02</span><div><span class="tag">PROJECT DISCUSSION</span><h2>Navigation & mobility</h2><p>Connect localization, planning and motion control around your robot’s operating environment and task.</p><ul><li>Waypoint and mission navigation requirements</li><li>Obstacle-aware planning and motion interfaces</li><li>Operating limits, supervision and recovery behavior</li></ul></div>${link('contact','Discuss navigation')}</article><article><span class="number">03</span><div><span class="tag">PROJECT DISCUSSION</span><h2>Integration & applied R&D</h2><p>Bring sensors, computing, ROS 2 software and robot platforms together around a defined engineering challenge.</p><ul><li>Architecture, robot interfaces and edge integration</li><li>Prototype and simulation-based evaluation</li><li>System testing and evidence-led development</li></ul></div>${link('contact','Discuss integration')}</article></section>
<section class="wrap section"><div class="section-heading">${label('How a project takes shape')}<h2>Define first.<br><span>Engineer with purpose.</span></h2></div><ol class="steps"><li><b>01 / Understand</b><p>Discuss the task, constraints and people involved.</p></li><li><b>02 / Scope</b><p>Agree the technical questions and what success means.</p></li><li><b>03 / Validate</b><p>Evaluate the approach against those requirements.</p></li><li><b>04 / Decide</b><p>Use the evidence to define the next stage.</p></li></ol></section>${cta}`,
research: `${intro('04 / Research & development','Ambition meets<br><span>engineering discipline.</span>','Our research and development priorities are robust localization, useful spatial perception, autonomous navigation and system-level integration. We focus on the questions that matter beyond a controlled demonstration.')}
<section class="wrap research-note"><span class="tag">DEVELOPMENT DIRECTION</span><p>This page describes our technical priorities. Public prototype demonstrations, performance results and deployment case studies are not yet published here.</p></section>
<section class="wrap section"><div class="three-grid">${card('01','Spatial understanding','How can sensing and localization remain useful when surfaces, lighting and visibility change?')}${card('02','Navigation & recovery','How should a robot plan useful motion, respond to obstacles and recover when localization or task execution is interrupted?')}${card('03','Field integration','How do hardware, software and human supervision work together within real operating constraints?')}</div></section>
<section class="wrap inset-section">${label('Our validation approach')}<h2>A demo is a beginning.<br><span>Evidence is the next step.</span></h2><div class="two-grid"><div><h3>Define the conditions</h3><p>State the environment, task, assumptions and limits before evaluating performance.</p><h3>Test recovery</h3><p>Consider interrupted tasks, uncertain perception and how a person takes control.</p></div><div><h3>Measure the work</h3><p>Evaluate task completion and quality—not just whether the robot moved.</p><h3>Document the result</h3><p>Record what was tested, what succeeded and what still needs development.</p></div></div></section>${cta}`,
about: `${intro('05 / About NorthBeam','Built here.<br><span>Thinking everywhere.</span>','NorthBeam Robotics is an autonomous robotics company being built in Hyderabad. We focus on autonomy software and integrated robotic systems, with a long-term ambition to make intelligent machines useful across industries.')}
<section class="wrap about-statement"><span class="large-n" aria-hidden="true">N</span><div>${label('Our conviction')}<h2>Robots matter<br>when they can<br><span>do useful work.</span></h2><p>We see robotics as a connection between intelligence and action. Useful systems need more than a capable algorithm: they need an understanding of the task, the machine and the environment.</p><p>Our foundation is perception, localization, autonomous navigation and robotics integration. Industries are applications of those capabilities—not boundaries around the company we are building.</p></div></section>
<section class="wrap section"><div class="section-heading">${label('What shapes our decisions')}<h2>Purpose before spectacle.<br><span>Progress through evidence.</span></h2></div><div class="three-grid">${card('01','Start with the work','Choose a real problem and understand how people solve it today.')}${card('02','Connect the whole system','Treat perception, hardware, control and operations as parts of one engineering challenge.')}${card('03','Earn the next step','Use measured results to guide development, expansion and deployment decisions.')}</div></section>${cta}`,
contact: `${intro('06 / Contact','What could we<br><span>build together?</span>','Tell us about your robot, the environment and the challenge. We welcome conversations about perception, localization, navigation and robotics integration projects.')}
<section class="wrap contact-grid"><div class="contact-panel">${label('Start a conversation')}<h2>Let’s talk robotics.</h2><a class="email-link" href="mailto:hello@northbeamrobotics.com">hello@northbeamrobotics.com <span aria-hidden="true">↗</span></a><p>Hyderabad, India</p><p class="small">The email link opens your email app. This website does not submit or store messages.</p></div><div class="contact-prompts"><h3>A useful starting point</h3><ol><li><b>The task</b><p>What physical work would you like to automate?</p></li><li><b>The environment</b><p>Where does it happen, and what constraints matter?</p></li><li><b>The outcome</b><p>What would a successful result look like?</p></li></ol><a class="button primary" href="mailto:hello@northbeamrobotics.com?subject=NorthBeam%20Robotics%20%E2%80%94%20Project%20enquiry">Write an enquiry <span aria-hidden="true">↗</span></a></div></section>`
};
for (const [slug,title] of pages) {
  const nav = pages.filter(([s])=>s!=='index').map(([s,t])=>`<a href="${s}.html" ${s===slug?'aria-current="page"':''} ${s==='contact'?'class="nav-contact"':''}>${t}</a>`).join('');
  const description = slug==='index'?'NorthBeam Robotics builds autonomy for the physical world: perception, localization, navigation and integrated robotic systems across industries.':`${title} at NorthBeam Robotics. Explore our robotics development direction, engineering approach and collaboration opportunities.`;
  const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${title==='Home'?'NorthBeam Robotics | Building autonomy for the physical world':title+' | NorthBeam Robotics'}</title><meta name="description" content="${description}"><meta name="theme-color" content="#060c17"><link rel="canonical" href="https://northbeamrobotics.com/${slug==='index'?'':slug+'.html'}"><link rel="icon" href="assets/northbeam-concept.svg" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="future.css?v=2"><script src="experience.js?v=1" defer></script></head>
<body data-page="${slug}"><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="wrap nav-wrap">${brand}<button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu <span aria-hidden="true">☰</span></button><nav id="navigation" aria-label="Main navigation">${nav}</nav></div></header><main id="main">${bodies[slug]}</main><footer class="wrap footer"><div>${brand}<p>Building autonomy for the physical world.</p></div><div class="footer-links"><a href="technology.html">Technology</a><a href="about.html">Company</a><a href="contact.html">Contact</a></div><div class="footer-meta"><span>HYDERABAD / INDIA</span><span>© ${new Date().getFullYear()} NorthBeam Robotics</span></div></footer></body></html>\n`;
  const cleanHtml = html
    .replace('<meta charset="utf-8">', `<meta charset="utf-8">${securityMeta}`)
    .replace(/href="([a-z]+)\.html"/g, (_,name) => `href="${cleanPath(name)}"`)
    .replace(/href="assets\//g, 'href="/assets/')
    .replace('href="future.css?v=2"', 'href="/future.css?v=2"')
    .replace('src="experience.js?v=1"', 'src="/experience.js?v=1"')
    .replace(`href="https://northbeamrobotics.com/${slug==='index'?'':slug+'.html'}"`, `href="https://northbeamrobotics.com${cleanPath(slug)}"`);
  if (slug==='index') {
    writeFileSync('index.html', cleanHtml);
  } else {
    mkdirSync(slug, {recursive:true});
    writeFileSync(`${slug}/index.html`, cleanHtml);
    // GitHub Pages cannot configure arbitrary server-side 301 rules. These
    // compatibility pages use a static refresh plus an accessible manual link.
    writeFileSync(`${slug}.html`, `<!doctype html>\n<html lang="en"><head><meta charset="utf-8">${securityMeta}<meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="refresh" content="0; url=${cleanPath(slug)}"><link rel="canonical" href="https://northbeamrobotics.com${cleanPath(slug)}"><title>${title} | NorthBeam Robotics</title><link rel="stylesheet" href="/future.css?v=2"></head><body><main class="page-intro wrap"><h1>This page has moved.</h1><p><a class="button primary" href="${cleanPath(slug)}">Continue to ${title}</a></p></main></body></html>\n`);
  }
}
console.log(`Built ${pages.length} clean-URL pages and ${pages.length-1} compatibility redirects with CSP.`);
