import { mkdirSync, writeFileSync } from 'node:fs';

// Meta CSP is supported by static GitHub Pages. Header-only protections such as
// frame-ancestors and HSTS must be configured at a hosting/proxy layer, not here.
const policy = "default-src 'none'; script-src 'self'; script-src-attr 'none'; style-src 'self' https://fonts.googleapis.com; style-src-attr 'none'; font-src https://fonts.gstatic.com; img-src 'self'; connect-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'; upgrade-insecure-requests";
const securityMeta = `<meta http-equiv="Content-Security-Policy" content="${policy}"><meta name="referrer" content="strict-origin-when-cross-origin">`;
const cleanPath = slug => slug==='index' ? '/' : `/${slug}/`;

const pages = [
  ['index','Home'],['technology','Technology'],['industries','Industries'],['solutions','Solutions'],['research','R&D'],['about','About'],['contact','Contact']
];
const link = (path, text, primary=false) => `<a class="button ${primary?'primary':''}" href="${path}.html">${text}<span aria-hidden="true">↗</span></a>`;
const label = text => `<p class="eyebrow">${text}</p>`;
const card = (n,title,body,tag='') => `<article class="card"><span class="number">${n}</span>${tag?`<span class="tag">${tag}</span>`:''}<h3>${title}</h3><p>${body}</p></article>`;
const intro = (n,title,body) => `<section class="page-intro wrap">${label(n)}<h1>${title}</h1><p class="lead">${body}</p></section>`;
const cta = `<section class="cta wrap"><div>${label('A conversation is the first step')}<h2>Bring us a<br><span>real-world challenge.</span></h2></div>${link('contact','Let’s talk',true)}</section>`;
const brand = `<a class="brand" href="index.html" aria-label="NorthBeam Robotics home"><span class="brand-symbol" aria-hidden="true">N</span><span>NORTHBEAM<small>R O B O T I C S</small></span></a>`;
const scene = (mode='brand') => `<div class="scene ${mode==='sense'?'sensor-scene':''}" data-scene="${mode}"><div class="scene-fallback" aria-hidden="true">N</div><canvas aria-label="${mode==='sense'?'Interactive conceptual 3D sensing illustration':'Interactive conceptual 3D NorthBeam N emblem'}" role="img"></canvas><div class="scene-top"><span>${mode==='sense'?'AUTONOMY / EXPLORER':'NORTHBEAM / FORM STUDY'}</span><span>3D</span></div><div class="scene-bottom"><span>${mode==='sense'?'SYNTHETIC DATA · NOT ROBOT TELEMETRY':'CONCEPTUAL BRAND VISUAL'}</span><button class="motion-toggle" type="button" aria-pressed="false">Pause motion</button></div></div>`;

const bodies = {
index: `<section class="home-hero wrap"><div class="hero-copy">${label('Robotics. Autonomy. Physical AI.')}<h1>Intelligence.<br>In <span>motion.</span></h1><p class="lead">We’re building intelligent machines for the world beyond the screen.</p><p class="hero-detail">From sensing to physical action. NorthBeam connects robotics, AI and engineering to tackle complex work across industries.</p><div class="actions">${link('technology','Explore our technology',true)}${link('about','Meet NorthBeam')}</div></div>${scene()}</section>
<div class="signal-strip"><div class="wrap"><span>HYDERABAD, INDIA</span><span>PERCEPTION / MOBILITY / MANIPULATION</span><span>BUILT FOR THE PHYSICAL WORLD</span></div></div>
<section class="wrap section"><div class="section-heading">${label('01 / The ambition')}<h2>Not one robot.<br><span>A world of possibilities.</span></h2><p>Different environments. Different challenges. A shared engineering foundation: understand the world, plan a response, and act with purpose.</p></div><div class="three-grid">${card('01','Understand','Perception and localization turn sensor measurements into an understanding of the environment.')}${card('02','Decide','Planning and control connect a task to a sequence of deliberate actions.')}${card('03','Act','Integrated machines bring autonomous decisions into the physical world.')}</div><div class="section-link">${link('technology','Inside the autonomy stack')}</div></section>
<section class="industry-feature wrap"><div>${label('02 / Our first focus')}<h2>Start with a<br><span>meaningful problem.</span></h2><p>Overhead installation is physically demanding work. Our initial development focus is robotic MEP installation—starting with cable-tray and conduit supports.</p>${link('industries','Explore our industry direction')}</div><div class="feature-type"><span class="tag">INITIAL DEVELOPMENT FOCUS</span><h3>Construction<br>& infrastructure<span class="outline-type">01</span></h3><p>Our starting point.<br>Not the limit of our ambition.</p></div></section>
<section class="wrap section"><div class="section-heading">${label('03 / Explore NorthBeam')}<h2>Engineering the<br><span>next chapter.</span></h2></div><div class="three-grid"><a class="editorial-card" href="solutions.html"><span class="number">SOLUTIONS</span><h3>From a challenge<br>to a scoped project.</h3><p>Explore possible ways to work together.</p><span class="card-link">Explore solutions ↗</span></a><a class="editorial-card" href="research.html"><span class="number">RESEARCH & DEVELOPMENT</span><h3>Progress starts<br>with better questions.</h3><p>Our technical priorities and validation approach.</p><span class="card-link">Inside R&D ↗</span></a><a class="editorial-card" href="about.html"><span class="number">THE COMPANY</span><h3>Built in Hyderabad.<br>Thinking beyond borders.</h3><p>The vision shaping NorthBeam Robotics.</p><span class="card-link">Our story ↗</span></a></div></section>${cta}`,
technology: `${intro('01 / Technology','From sensing<br>to <span>physical action.</span>','Autonomy is a connected system. Perception, localization, planning and control have to work together—not just work in isolation.')}
<section class="wrap explorer"><div class="explorer-heading"><div>${label('Explore the autonomy loop')}<h2>One environment.<br><span>Three perspectives.</span></h2></div><div class="mode-controls" role="group" aria-label="Visualization mode"><button data-mode="sense" aria-pressed="true">01 Sense</button><button data-mode="map" aria-pressed="false">02 Map</button><button data-mode="plan" aria-pressed="false">03 Plan</button></div></div>${scene('sense')}<div class="explorer-caption"><h3 id="mode-title">Sense the surroundings</h3><p id="mode-description" aria-live="polite">A synthetic point cloud illustrates how spatial measurements can describe surfaces and obstacles. This is an explanatory visual, not a working perception system.</p></div><noscript><p>The static view illustrates the sensing stage. Enable JavaScript to switch between sensing, mapping and planning.</p></noscript></section>
<section class="wrap section"><div class="two-grid">${card('01','Perception & sensor fusion','Combining 3D sensing and computer vision to estimate where objects and surfaces are, while accounting for incomplete or uncertain measurements.')}${card('02','Localization & mapping','Estimating a robot’s position within an environment. Robust operation depends on reference frames, map quality and recovery from localization loss.')}${card('03','Planning & motion control','Turning a task into a feasible path and controlled motion, with explicit operating limits and responses to obstacles.')}${card('04','Manipulation & integration','Connecting software to mechanisms, actuators and end-effectors designed around the physical task.')}</div></section>
<section class="wrap inset-section">${label('Engineering principle')}<h2>Autonomy needs<br><span>boundaries.</span></h2><p class="lead">Defined operating conditions, human supervision, fault handling and task-specific validation belong in the design from the beginning.</p><p>These are engineering priorities, not a claim of certified safety or unrestricted autonomous operation.</p></section>${cta}`,
industries: `${intro('02 / Industries','Many industries.<br><span>One physical world.</span>','We’re interested in work that is repetitive, physically demanding or difficult to perform consistently. Construction is our starting point, with wider applications to explore.')}
<section class="wrap industry-lead"><div>${label('01 / Initial development focus')}<h2>Construction<br><span>& infrastructure.</span></h2><p class="lead">Robotic overhead MEP installation, starting with cable-tray and conduit supports.</p><p>The proposed model is outcome-based: customers buy completed, verified installation work rather than owning a robot. Technical feasibility and site-specific requirements must be validated before deployment.</p>${link('contact','Discuss a potential pilot',true)}</div><aside><h3>The work we’re targeting</h3><ul class="detail-list"><li><span>Task</span>Overhead support installation</li><li><span>Setting</span>Built environments with repeatable work</li><li><span>Approach</span>Task-specific robotic integration</li><li><span>Status</span>Development focus—not a launched product</li></ul></aside></section>
<section class="wrap section"><div class="section-heading">${label('02 / Future exploration')}<h2>The next<br><span>frontiers.</span></h2><p>Directions for future development, not a catalogue of deployed solutions.</p></div><div class="two-grid">${card('02','Manufacturing & industrial work','Explore repeatable handling, process assistance and physically demanding tasks within defined industrial environments.','FUTURE DIRECTION')}${card('03','Logistics & material movement','Explore autonomous movement and coordination in structured operational spaces.','FUTURE DIRECTION')}${card('04','Inspection & asset intelligence','Explore mobile sensing and visual analysis to help people understand asset condition.','FUTURE DIRECTION')}${card('05','Complex autonomous operations','Explore how robots can support people working across large or changing environments.','FUTURE DIRECTION')}</div></section>${cta}`,
solutions: `${intro('03 / Solutions','The right approach.<br><span>For the actual work.</span>','Every robotics project starts with a task, an environment and a clear definition of success. The routes below are starting points for discussion; scope and availability are agreed individually.')}
<section class="wrap solution-list"><article><span class="number">01</span><div><span class="tag">PROJECT DISCUSSION</span><h2>Autonomy development</h2><p>Explore perception, localization, navigation and control around your robot and operating environment.</p><ul><li>Task and environment review</li><li>Software architecture and integration scope</li><li>Simulation and validation requirements</li></ul></div>${link('contact','Discuss autonomy')}</article><article><span class="number">02</span><div><span class="tag">PROJECT DISCUSSION</span><h2>Robotics integration</h2><p>Bring sensing, computation, mechanisms and software together around a specific physical task.</p><ul><li>System interfaces and hardware constraints</li><li>Human supervision and operating boundaries</li><li>Prototype evaluation and acceptance criteria</li></ul></div>${link('contact','Discuss integration')}</article><article><span class="number">03</span><div><span class="tag">PROPOSED DELIVERY MODEL</span><h2>Robotics-as-a-Service</h2><p>A proposed outcome-based approach to overhead installation: robotic capability delivered around completed work, not a hardware sale.</p><ul><li>Site-specific feasibility assessment</li><li>Agreed work scope and verification method</li><li>Pilot validation before scaled deployment</li></ul></div>${link('contact','Explore a pilot')}</article></section>
<section class="wrap section"><div class="section-heading">${label('How a project takes shape')}<h2>Define first.<br><span>Engineer with purpose.</span></h2></div><ol class="steps"><li><b>01 / Understand</b><p>Discuss the task, constraints and people involved.</p></li><li><b>02 / Scope</b><p>Agree the technical questions and what success means.</p></li><li><b>03 / Validate</b><p>Evaluate the approach against those requirements.</p></li><li><b>04 / Decide</b><p>Use the evidence to define the next stage.</p></li></ol></section>${cta}`,
research: `${intro('04 / Research & development','Ambition meets<br><span>engineering discipline.</span>','Our development direction connects machine perception to useful physical work. We focus on questions that matter when a robot leaves a controlled demonstration.')}
<section class="wrap research-note"><span class="tag">DEVELOPMENT DIRECTION</span><p>This page describes our technical priorities. Public prototype demonstrations, performance results and deployment case studies are not yet published here.</p></section>
<section class="wrap section"><div class="three-grid">${card('01','Spatial understanding','How can sensing and localization remain useful when surfaces, lighting and visibility change?')}${card('02','Task-level autonomy','How should a robot translate a work objective into actions it can execute and verify?')}${card('03','Field integration','How do hardware, software and human supervision work together within real operating constraints?')}</div></section>
<section class="wrap inset-section">${label('Our validation approach')}<h2>A demo is a beginning.<br><span>Evidence is the next step.</span></h2><div class="two-grid"><div><h3>Define the conditions</h3><p>State the environment, task, assumptions and limits before evaluating performance.</p><h3>Test recovery</h3><p>Consider interrupted tasks, uncertain perception and how a person takes control.</p></div><div><h3>Measure the work</h3><p>Evaluate task completion and quality—not just whether the robot moved.</p><h3>Document the result</h3><p>Record what was tested, what succeeded and what still needs development.</p></div></div></section>${cta}`,
about: `${intro('05 / About NorthBeam','Built here.<br><span>Thinking everywhere.</span>','NorthBeam Robotics is being built in Hyderabad with a long-term ambition: make intelligent machines practical across the industries that shape the physical world.')}
<section class="wrap about-statement"><span class="large-n" aria-hidden="true">N</span><div>${label('Our conviction')}<h2>Robots matter<br>when they can<br><span>do useful work.</span></h2><p>We see robotics as a connection between intelligence and action. Useful systems need more than a capable algorithm: they need an understanding of the task, the machine and the environment.</p><p>Our initial focus is construction automation. Our broader vision reaches beyond a single task, industry or robot form.</p></div></section>
<section class="wrap section"><div class="section-heading">${label('What shapes our decisions')}<h2>Purpose before spectacle.<br><span>Progress through evidence.</span></h2></div><div class="three-grid">${card('01','Start with the work','Choose a real problem and understand how people solve it today.')}${card('02','Connect the whole system','Treat perception, hardware, control and operations as parts of one engineering challenge.')}${card('03','Earn the next step','Use measured results to guide development, expansion and deployment decisions.')}</div></section>${cta}`,
contact: `${intro('06 / Contact','What could we<br><span>build together?</span>','Tell us about the work, the environment and the challenge. We welcome conversations about potential projects, pilots and engineering collaboration.')}
<section class="wrap contact-grid"><div class="contact-panel">${label('Start a conversation')}<h2>Let’s talk robotics.</h2><a class="email-link" href="mailto:hello@northbeamrobotics.com">hello@northbeamrobotics.com <span aria-hidden="true">↗</span></a><p>Hyderabad, India</p><p class="small">The email link opens your email app. This website does not submit or store messages.</p></div><div class="contact-prompts"><h3>A useful starting point</h3><ol><li><b>The task</b><p>What physical work would you like to automate?</p></li><li><b>The environment</b><p>Where does it happen, and what constraints matter?</p></li><li><b>The outcome</b><p>What would a successful result look like?</p></li></ol><a class="button primary" href="mailto:hello@northbeamrobotics.com?subject=NorthBeam%20Robotics%20%E2%80%94%20Project%20enquiry">Write an enquiry <span aria-hidden="true">↗</span></a></div></section>`
};
for (const [slug,title] of pages) {
  const nav = pages.filter(([s])=>s!=='index').map(([s,t])=>`<a href="${s}.html" ${s===slug?'aria-current="page"':''} ${s==='contact'?'class="nav-contact"':''}>${t}</a>`).join('');
  const description = slug==='index'?'NorthBeam Robotics — intelligence in motion. Robotics, autonomy and physical AI from Hyderabad.':`${title} at NorthBeam Robotics. Explore our robotics development direction, engineering approach and collaboration opportunities.`;
  const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${title==='Home'?'NorthBeam Robotics | Intelligence in motion':title+' | NorthBeam Robotics'}</title><meta name="description" content="${description}"><meta name="theme-color" content="#060c17"><link rel="canonical" href="https://northbeamrobotics.com/${slug==='index'?'':slug+'.html'}"><link rel="icon" href="assets/northbeam-concept.svg" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="future.css?v=1"><script src="experience.js?v=1" defer></script></head>
<body data-page="${slug}"><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="wrap nav-wrap">${brand}<button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu <span aria-hidden="true">☰</span></button><nav id="navigation" aria-label="Main navigation">${nav}</nav></div></header><main id="main">${bodies[slug]}</main><footer class="wrap footer"><div>${brand}<p>Intelligence for the physical world.</p></div><div class="footer-links"><a href="technology.html">Technology</a><a href="about.html">Company</a><a href="contact.html">Contact</a></div><div class="footer-meta"><span>HYDERABAD / INDIA</span><span>© ${new Date().getFullYear()} NorthBeam Robotics</span></div></footer></body></html>\n`;
  const cleanHtml = html
    .replace('<meta charset="utf-8">', `<meta charset="utf-8">${securityMeta}`)
    .replace(/href="([a-z]+)\.html"/g, (_,name) => `href="${cleanPath(name)}"`)
    .replace(/href="assets\//g, 'href="/assets/')
    .replace('href="future.css?v=1"', 'href="/future.css?v=1"')
    .replace('src="experience.js?v=1"', 'src="/experience.js?v=1"')
    .replace(`href="https://northbeamrobotics.com/${slug==='index'?'':slug+'.html'}"`, `href="https://northbeamrobotics.com${cleanPath(slug)}"`);
  if (slug==='index') {
    writeFileSync('index.html', cleanHtml);
  } else {
    mkdirSync(slug, {recursive:true});
    writeFileSync(`${slug}/index.html`, cleanHtml);
    // GitHub Pages cannot configure arbitrary server-side 301 rules. These
    // compatibility pages use a static refresh plus an accessible manual link.
    writeFileSync(`${slug}.html`, `<!doctype html>\n<html lang="en"><head><meta charset="utf-8">${securityMeta}<meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="refresh" content="0; url=${cleanPath(slug)}"><link rel="canonical" href="https://northbeamrobotics.com${cleanPath(slug)}"><title>${title} | NorthBeam Robotics</title><link rel="stylesheet" href="/future.css?v=1"></head><body><main class="page-intro wrap"><h1>This page has moved.</h1><p><a class="button primary" href="${cleanPath(slug)}">Continue to ${title}</a></p></main></body></html>\n`);
  }
}
console.log(`Built ${pages.length} clean-URL pages and ${pages.length-1} compatibility redirects with CSP.`);
